#:import utils kivy.utils


<PlantillaPre>:
    BoxLayout:
        orientation: 'vertical'
        size_hint: 1,1 
        spacing: 9       
        BackgroundBoxLayout:
            spacing: 9
            orientation: 'horizontal' 
            background_color: 0.97,0.79,0.89,1
            size_hint: 1,0.5

            BackgroundLabel:
                id:'ParteArrib2a'
                background_color: 0.97,0.79,0.89,1
                size_hint: 1,0.6
                text: 'GUIA EVALUATIVA  \n DE PRESERVATIVOS '
                halign: 'center'
                font_size: '14sp'
               
            Image:
                size_hint: .95, .95
                source: './images/condon.png'
                    
        BoxLayout:
            orientation: 'vertical'
            size_hint: 1,0.8
            spacing: 9
            BackgroundLabel:
                id:'ParteMedia'
                background_color: 0.61,0.61,0.61,1
                size_hint: 1,.6
                text: 'INSTRUCCIONES:\n Completa todos los ejercicios  que se  te presentan \ny acumula puntos'
                font_size: '12sp'
                halign: 'center'
        BoxLayout:
            orientation: 'vertical'
            size_hint: 1,0.5
            BackgroundLabel:
                id:'PartePreguntas'
                background_color: 0.61,0.61,0.61,1
                size_hint: 1,0.2
                text: 'PREGUNTAS'
                font_size: '10sp'
                halign: 'center'
        BoxLayout:
            orientation: 'vertical'
            size_hint: 1,0.4
            BackgroundLabel:
                id:'PartePreguntas'
                size_hint: 1,.4
                text: '1. Los condones son efectivos contra el VIH \n y otras Enfermedades de transmisión \nsexual, verdadero o falso?'
                font_size: '12sp'
                halign: 'center'
        BackgroundBoxLayout:
            orientation: 'horizontal'
            size_hint: .9,.2
            spacing: 10
                
            Button:
                text: 'Verdadero'
                on_press: root.save_gender("V")
                
            Button:
                text: 'Falso'
                on_press: root.save_gender("F")
               

        BoxLayout:
            orientation: 'vertical'
            size_hint: 1,.4
            BackgroundLabel:
                id:'PartePreguntas'
                size_hint: 1,.4
                text: '2. Un condón es una cubierta delgada\n usada en el pene durante \nel coito, verdadero o falso?'
                font_size: '12sp'
                halign: 'center'
        BackgroundBoxLayout:
            orientation: 'horizontal'
            size_hint: .9,.2
            spacing: 10
                
            Button:
                text: 'Verdadero'
                on_press: root.save_gender("V")
                
            Button:
                text: 'Falso'
                on_press: root.save_gender("F")
        BoxLayout:
            orientation: 'vertical'
            size_hint: 1,.3
            BackgroundLabel:
                id:'PartePreguntas'
                text: '3. Los condones son frágiles y delicados,\n  verdadero o falso?'
                font_size: '12sp'
                halign: 'center'
                size_hint: 1,.4
        BackgroundBoxLayout:
            orientation: 'horizontal'
            size_hint: .9,.2
            spacing: 10
                
            Button:
                text: 'Verdadero'
                on_press: root.save_gender("V")
                
            Button:
                text: 'Falso'
                on_press: root.save_gender("F")
        BoxLayout:
            orientation: 'vertical'
            size_hint: 1,.75
            BackgroundLabel:
                id:'PartePreguntas'
                text: '4. Existen variedades de preservativos, tales como: \nCon o sin lubricante, \nCon o sin depósito para semen, \nFinos o gruesos,De colores y sabores, \n verdadero o falso?'
                font_size: '12sp'
                halign: 'center'
                size_hint: 1,.4
        BackgroundBoxLayout:
            orientation: 'horizontal'
            size_hint: .9,.2
            spacing: 10
                
            Button:
                text: 'Verdadero'
                on_press: root.save_gender("V")
                
            Button:
                text: 'Falso'
                on_press: root.save_gender("F")
        BoxLayout:
            orientation: 'vertical'
            size_hint: 1,.4
            BackgroundLabel:
                id:'PartePreguntas'
                text: '5. Los condones pueden ser reutilizados, \nverdadero o falso?'
                font_size: '12sp'
                halign: 'center'
                size_hint: 1,.4

        BackgroundBoxLayout:
            orientation: 'horizontal'
            size_hint: .9,.2
            spacing: 10
                
            Button:
                text: 'Verdadero'
                on_press: root.save_gender("V")
                
            Button:
                text: 'Falso'
                on_press: root.save_gender("F")
        BackgroundBoxLayout:
            orientation: 'horizontal'
            size_hint: 1,.5
            spacing: 10
                
            Button:
                text: 'Calificar'
                background_color: 0.56,0.56,0.561,.7
        

                
           
                            
    


