
<CondonI>:
    BoxLayout:
        orientation: 'vertical'

        AnchorLayout:
            size_hint: 1, .6
            Image:
                size_hint: .5, .7
                source: 'images/circulo.png'

            Image:
                size_hint: .3, .4
                source: 'images/cinterno.png'

        BoxLayout:
            orientation: 'vertical'
            padding: 50, 0, 50, 30
            size_hint: 1, .2
                
            BackgroundLabel:
                bold: True
                text: 'Condón Interno'
                font_size: '20sp'
                color: 0,0,0,1
                size_hint: 1, .2
                background_color: 0.97, 0.79, 0.89, 1

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            padding: 50, 20, 50, 20

            Label:
                size_hint_y: None
                color: 0,0,0,1
                text_size: self.width, None
                height: self.texture_size[1]
                padding: 50, 50

                text:
                    '''\n\nLos condones internos poseen un 79% de efectividad. Si se usa de una manera correcta, ya sea usánsolo durando todo el acto sexual y colocándolo de una forma correcta, ya sea en la vagina o en el ano puede llegar a ser bastante efectivo.\n\nLos condones internos no poseen efectos secundarios.\n\nLos condones internos son ideales para evitar el embarazo y la transmisión de enfermedades sexuales.\n\n(Planned Parenthood, 2022)'''

        BoxLayout:
            orientation: 'horizontal'
            spacing: 20
            #derecha arriba izquierda abajo
            padding: 50, 30, 50, 30
            size_hint: 1, .2

            RoundedButton:
                text: 'Regresar'
                on_press: root.manager.current = 'preservativos'
            RoundedButton:
                text: 'Agregar'
                on_press: root.save_gender("F")

